name: ijcai-17
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py27_0
  - astor=0.8.0=py27_0
  - backports=1.0=py_2
  - backports.weakref=1.0.post1=py_1
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py27_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cupti=10.0.130=0
  - enum34=1.1.6=py27_1
  - funcsigs=1.0.2=py27_0
  - future=0.18.2=py27_0
  - futures=3.3.0=py27_0
  - gast=0.2.2=py27_0
  - google-pasta=0.1.8=py_0
  - grpcio=1.16.1=py27hf8bcb03_1
  - h5py=2.9.0=py27h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - intel-openmp=2019.4=243
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_0
  - libprotobuf=3.11.2=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - linecache2=1.0.0=py27_0
  - mako=1.1.1=py_0
  - markdown=3.1.1=py27_0
  - markupsafe=1.1.1=py27h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py27he904b0f_0
  - mkl_fft=1.0.15=py27ha843d7b_0
  - mkl_random=1.1.0=py27hd6b4f25_0
  - mock=2.0.0=py27_0
  - ncurses=6.1=he6710b0_1
  - numpy-base=1.16.5=py27hde5b4d6_0
  - openssl=1.1.1d=h7b6447c_4
  - opt_einsum=2.3.2=py_0
  - pbr=5.4.4=py_0
  - pip=19.3.1=py27_0
  - protobuf=3.11.2=py27he6710b0_0
  - pygpu=0.7.6=py27h035aef0_0
  - python=2.7.17=h9bab390_0
  - readline=7.0=h7b6447c_5
  - setuptools=44.0.0=py27_0
  - six=1.13.0=py27_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorboard=1.15.0=py27hb230dea_0
  - tensorflow=1.15.0=gpu_py27h0c9f15b_0
  - tensorflow-base=1.15.0=gpu_py27hf473bbb_0
  - tensorflow-estimator=1.15.1=pyh2649769_0
  - tensorflow-gpu=1.15.0=h0d30ee6_0
  - termcolor=1.1.0=py27_1
  - tk=8.6.8=hbc83047_0
  - traceback2=1.4.0=py27_0
  - unittest2=1.1.0=py27_0
  - webencodings=0.5.1=py27_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py27_0
  - wrapt=1.11.2=py27h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - backports-functools-lru-cache==1.6.1
    - cycler==0.10.0
    - keras==1.2.1
    - kiwisolver==1.1.0
    - matplotlib==2.2.4
    - numpy==1.16.6
    - pandas==0.24.2
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyyaml==5.3
    - scikit-learn==0.20.4
    - scipy==1.2.2
    - sklearn==0.0
    - subprocess32==3.5.4
    - theano==1.0.4

